// <auto-generated />
namespace C__project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changedname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedname));
        
        string IMigrationMetadata.Id
        {
            get { return "202402090053525_changed-name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
